version: '3.8'

services:
  cf-ddns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cf-ddns
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam # Set your preferred timezone